### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RuslanFF** [DRAGKILLS/MCBE-Proxy#2]
Fatal error: Uncaught Error: Cannot access private constant raklib\server\Session::MAX_SPLIT_SIZE in /storage/emulated/0/Download/ProxyMcbe/src/proxy/utils/Packet.php:65
Stack trace:
#0 /storage/emulated/0/Download/ProxyMcbe/src/proxy/utils/Packet.php(48): proxy\utils\Packet::decodeSplit(Object(raklib\protocol\EncapsulatedPacket))
#1 /storage/emulated/0/Download/ProxyMcbe/src/proxy/Proxy.php(99): proxy\utils\Packet::readDataPacket('\x84\x05\x00\x00p,\xC0\x02\x00\x00\x01\x00\x00\x00\x00...')
#2 /storage/emulated/0/Download/ProxyMcbe/src/proxy/Proxy.php(84): proxy\Proxy->decodeBuffer('\x84\x05\x00\x00p,\xC0\x02\x00\x00\x01\x00\x00\x00\x00...', Object(proxy\hosts\Client))
#3 /storage/emulated/0/Download/ProxyMcbe/src/proxy/start.php(27): proxy\Proxy->__construct('CCodyCore.aternos.me', 41612, '0.0.0.0', 54975, false)
#4 {main}
  thrown in /storage/emulated/0/Download/ProxyMcbe/src/proxy/utils/Packet.php on line 65

**Comment by DRAGKILLS** [comment]
I will check it

**Comment by DRAGKILLS** [comment]
now u can try

**Comment by DRAGKILLS** [comment]
And i will update it to 1.17.30 soon
